# Generated by Django 4.1 on 2023-10-26 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('productId', models.AutoField(primary_key=True, serialize=False)),
                ('productName', models.CharField(max_length=100)),
                ('productDescription', models.CharField(max_length=240)),
                ('listPrice', models.FloatField(default=0.0, verbose_name='listPrice')),
                ('slaesPrice', models.FloatField(default=0.0, verbose_name='slaesPrice')),
                ('productImage', models.CharField(max_length=240)),
                ('productStock', models.CharField(max_length=240)),
                ('productFeatures', models.CharField(max_length=240)),
                ('currency', models.CharField(max_length=240)),
            ],
        ),
    ]
